# -*- coding: utf-8 -*-
"""ListasYDiccionarios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/147j7rc0PfrSgBhnMJV-JM5S_fMruM7Hi

Ejercicio 1: Manipulación de Listas
Crea una lista llamada nombres que contenga los siguientes elementos: "Juan", "Ana",
"Luis", "Pedro". Luego, realiza las siguientes tareas:
1. Modifica el tercer elemento de la lista para que ahora sea "Carlos".
2. Agrega un nuevo nombre "Lucía" al final de la lista.
3. Elimina el primer nombre de la lista.
4. Muestra todos los elementos de la lista en una sola línea sin corchetes ni comas.
5. Imprime la cantidad total de nombres en la lista
"""

nombres=["juan","Ana","Luis","pedro"]
#Modifica el tercer elemento de la lista para que ahora sea "Carlos"
nombres.pop(2)
print(nombres)
#Agrega un nuevo nombre "Lucía" al final de la lista.
nombres.append("Lucia")
print(nombres)
#Elimina el primer nombre de la lista.
nombres.pop(0)
print(nombres)
#Muestra todos los elementos de la lista en una sola línea sin corchetes ni comas.
print(*nombres)
#Imprime la cantidad total de nombres en la lista
print("este es el numero total de elementos",len(nombres))

"""Ejercicio 2: Diccionarios Básicos
Crea un diccionario llamado edades que almacene la edad de las siguientes personas:
"Juan": 25, "Ana": 30, "Luis": 28. Realiza las siguientes tareas:
1. Accede y muestra la edad de Ana.
2. Cambia la edad de Luis a 29.
3. Agrega un nuevo par clave-valor al diccionario con el nombre "Pedro" y la edad de 22.
4. Elimina el registro de Juan del diccionario.
5. Muestra el diccionario final con las edades actualizadas.
"""

edades={
    "juan" : [25],
    "Ana" : [30],
    "Luis" : [28]
    }
#Accede y muestra la edad de Ana.
print(edades["Ana"][0])
#Cambia la edad de Luis a 29
edades["Luis"]= [29]
print(edades)
#Agrega un nuevo par clave-valor al diccionario con el nombre "Pedro" y la edad de 22.
edades["pedro"] = [22]
print(edades)
#Elimina el registro de Juan del diccionario.
del edades["juan"]
print(edades)
#Muestra el diccionario final con las edades actualizadas.
print(edades)

"""Ejercicio 3: Diccionarios Anidados
Imagina que tienes un diccionario llamado libros que almacena información sobre varios
libros. El diccionario inicial es el siguiente:
Realiza las siguientes tareas:
1. Accede y muestra el autor de Don Quijote de la Mancha.
2. Agrega un nuevo libro al diccionario con la siguiente información: título
"Fahrenheit 451", autor "Ray Bradbury", año 1953, género "Ciencia
Ficción".
3. Modifica el año de publicación de Cien Años de Soledad a 1965.
4. Muestra todos los títulos de libros disponibles en el diccionario
"""

libros={
    "cien años de soledad" : {
        "autor" : "Gabriel Garcia Marquez",
        "Año" : 1967,
        "Genereo" : "realismo magico"
    },
    "Don quijote de la mancha" : {
        "autor" : "Miguel de Cervantes Saavedra",
        "año" : 1605,
        "genero" : "Novela"
    }
}
#Accede y muestra el autor de Don Quijote de la Mancha.
print(*libros["Don quijote de la mancha"]["autor"])

#Agrega un nuevo libro al diccionario con la siguiente información: título "Fahrenheit 451", autor "Ray Bradbury", año 1953, género "Ciencia Ficción".
libros["Fahrenheit 451"]= {
    "autor" : "Ray Bradbury",
    "año" : 1953,
    "Genero" : "Ciencia Ficcion"
}
print(libros)
#Modifica el año de publicación de Cien Años de Soledad a 1965.
libros['cien años de soledad']["Año"] = [1965]
print(libros["cien años de soledad"])
#Muestra todos los títulos de libros disponibles en el diccionario

titutlosLibros = libros
for i,libro in enumerate(titutlosLibros, start=1):
  print(f"titulos {i}", libro )

"""Ejercicio 4: Iteración y Enumeración en Listas
Crea una lista llamada colores que contenga los siguientes elementos: "Rojo",
"Verde", "Azul", "Amarillo". Luego, realiza las siguientes tareas:
1. Utilizando un bucle for, imprime cada color de la lista junto con su posición en la
lista (utiliza enumerate).
2. Modifica la lista para que el primer color sea "Naranja".
3. Elimina el último color de la lista.
4. Muestra la lista final.

"""

#Utilizando un bucle for, imprime cada color de la lista junto con su posición en la lista (utiliza enumerate)
colores=["Rojo","Verde","Azul","Amarillo"]

for i, color in enumerate(colores, start=1):
  print(f"color numero {i}: {color}")
#Modifica la lista para que el primer color sea "Naranja"
colores[0]= "naranja"
print(*colores)
#Elimina el último color de la lista.
del colores[3]
#Muestra la lista final.
print(*colores)

"""Ejercicio 5: Enumerar Productos en un Inventario
Tienes un diccionario llamado inventario que contiene el nombre de varios productos y
una lista con las cantidades disponibles en diferentes almacenes. El diccionario es el
siguiente:
Realiza las siguientes tareas:
1. Utiliza un bucle for con enumerate para iterar sobre la lista de cantidades de
"Manzanas" e imprime cada cantidad junto con el número de almacén
(comenzando desde 1).
2. Haz lo mismo para las cantidades de "Plátanos"
"""

inventario = {
    "Manzanas": [100, 150, 200],
    "Naranjas": [50,80,120],
    "peras": [75,60,90],
    "Platanos": [40,30,50]
}
# --Utiliza un bucle for con enumerate para iterar sobre la lista de cantidades de "Manzanas"
#   e imprime cada cantidad junto con el número de almacén (comenzando desde 1).
manzanasNum = inventario["Manzanas"]
print("Este es el almacen de manzanas")
for i, fruta in enumerate(manzanasNum, start=1):
  print(f"numero de almacen {i} : ", fruta)

# Haz lo mismo para las cantidades de "Plátanos"

platanosNum = inventario["Platanos"]
print("Este es el almacen de platanos")

for i, frut in enumerate(platanosNum, start=1):
  print(f"el numero de almacen es {i}: ", frut)